


/*This script has been, partially or completely, generated by the Amanita.GenerateVariableWindow*/
using UnityEngine;
using UnityEngine.Audio;


namespace Amanita.VScripting
{
	/// <summary>
	/// AudioMixer variable type.
	/// </summary>
	[VariableInfo("Other", "AudioMixer")]
	[AddComponentMenu("")]
	[System.Serializable]
	public class AudioMixerVariable : VariableBase<AudioMixer>
	{ }

	/// <summary>
	/// Container for a AudioMixer variable reference or constant value.
	/// </summary>
	[System.Serializable]
	[VariableData(typeof(AudioMixer), typeof(AudioMixerVariable))]
	public class AudioMixerData : VariableData<AudioMixer, IVariable<AudioMixer>>
	{
		[SerializeField]
		[VariableProperty("<Value>", typeof(AudioMixerVariable))]
		public AudioMixerVariable audioMixerRef;


		public static implicit operator UnityEngine.Audio.AudioMixer(AudioMixerData AudioMixerData)
		{
			return AudioMixerData.Value;
		}


		public AudioMixerData() : base(default) { }
		public AudioMixerData(AudioMixer startVal = null) : base(startVal) { }

		public override IVariable VarRef
		{
			get { return audioMixerRef; }
			set
			{
				if (value == null) { audioMixerRef = null; return; }

				if (value.ContentType.Equals(this.ContentType))
				{
					audioMixerRef = value as AudioMixerVariable;
				}
				else
				{
					string errorMessage = $"This can only accept a variable type that holds content of type {ContentType.Name}.";
					throw new System.InvalidCastException(errorMessage);
				}

			}
		}
	}
}