


/*This script has been, partially or completely, generated by the Amanita.GenerateVariableWindow*/
using UnityEngine;


namespace Amanita.VScripting
{
	/// <summary>
	/// Character variable type.
	/// </summary>
	[VariableInfo("Other", "Character")]
	[AddComponentMenu("")]
	[System.Serializable]
	public class CharacterVariable : VariableBase<Amanita.Character>
	{ }

	/// <summary>
	/// Container for a Character variable reference or constant value.
	/// </summary>
	[System.Serializable]
	public struct CharacterData
	{
		[SerializeField]
		[VariableProperty("<Value>", typeof(CharacterVariable))]
		public CharacterVariable characterRef;

		[SerializeField]
		public Amanita.Character characterVal;

		public static implicit operator Amanita.Character(CharacterData CharacterData)
		{
			return CharacterData.Value;
		}

		public CharacterData(Amanita.Character v)
		{
			characterVal = v;
			characterRef = null;
		}

		public Amanita.Character Value
		{
			get { return (characterRef == null) ? characterVal : characterRef.Value; }
			set { if (characterRef == null) { characterVal = value; } else { characterRef.Value = value; } }
		}

		public string GetDescription()
		{
			if (characterRef == null)
			{
				return characterVal != null ? characterVal.ToString() : "Null";
			}
			else
			{
				return characterRef.Key;
			}
		}
	}
}