


/*This script has been, partially or completely, generated by the Amanita.GenerateVariableWindow*/

using UnityEngine;

namespace Amanita.VScripting
{
    /// <summary>
    /// Collision2D variable type.
    /// </summary>
    [VariableInfo("Other", "Collision2D", IsPreviewedOnly = true)]
    [AddComponentMenu("")]
    [System.Serializable]
    public class Collision2DVariable : VariableBase<UnityEngine.Collision2D>
    { }
}