


/*This script has been, partially or completely, generated by the Amanita.GenerateVariableWindow*/

using UnityEngine;

namespace Amanita.VScripting
{
    /// <summary>
    /// Collision variable type.
    /// </summary>
    [VariableInfo("Other", "Collision", IsPreviewedOnly = true)]
    [AddComponentMenu("")]
    [System.Serializable]
    public class CollisionVariable : VariableBase<UnityEngine.Collision>
    { }
}