


/*This script has been, partially or completely, generated by the Amanita.GenerateVariableWindow*/

using UnityEngine;

namespace Amanita.VScripting
{
    /// <summary>
    /// ControllerColliderHit variable type.
    /// </summary>
    [VariableInfo("Other", "ControllerColliderHit", IsPreviewedOnly = true)]
    [AddComponentMenu("")]
    [System.Serializable]
    public class ControllerColliderHitVariable : VariableBase<UnityEngine.ControllerColliderHit>
    { }
}