/*This script has been, partially or completely, generated by the Amanita.GenerateVariableWindow*/

using UnityEditor;

namespace Amanita.VScripting.EditorUtils
{
    [CustomPropertyDrawer(typeof(Collider2DData))]
    public class Collider2DDataDrawer : VariableDataDrawer<Collider2DVariable>
    { }
}