/*This script has been, partially or completely, generated by the Amanita.GenerateVariableWindow*/

using UnityEditor;

namespace Amanita.VScripting.EditorUtils
{
    [CustomPropertyDrawer(typeof(Matrix4x4Data))]
    public class Matrix4x4DataDrawer : VariableDataDrawer<Matrix4x4Variable>
    { }
}