/*This script has been, partially or completely, generated by the Amanita.GenerateVariableWindow*/

using UnityEditor;

namespace Amanita.VScripting.EditorUtils
{
    [CustomPropertyDrawer(typeof(Vector4Data))]
    public class Vector4DataDrawer : VariableDataDrawer<Vector4Variable>
    { }
}