/*This script has been, partially or completely, generated by the Amanita.GenerateVariableWindow*/

using UnityEditor;

namespace Amanita.VScripting.EditorUtils
{
    [CustomPropertyDrawer(typeof(Rigidbody2DData))]
    public class Rigidbody2DDataDrawer : VariableDataDrawer<Rigidbody2DVariable>
    { }
}