/*This script has been, partially or completely, generated by the Amanita.GenerateVariableWindow*/

using UnityEditor;

namespace Amanita.VScripting.EditorUtils
{
    [CustomPropertyDrawer(typeof(AnimatorData))]
    public class AnimatorDataDrawer : VariableDataDrawer<AnimatorVariable>
    { }
}