/*This script has been, partially or completely, generated by the Amanita.GenerateVariableWindow*/

using UnityEditor;

namespace Amanita.VScripting.EditorUtils
{
    [CustomPropertyDrawer(typeof(Vector3Data))]
    public class Vector3DataDrawer : VariableDataDrawer<Vector3Variable>
    { }
}