/*This script has been, partially or completely, generated by the Amanita.GenerateVariableWindow*/

using UnityEditor;

namespace Amanita.VScripting.EditorUtils
{
    [CustomPropertyDrawer(typeof(Vector2Data))]
    public class Vector2DataDrawer : VariableDataDrawer<Vector2Variable>
    { }
}